# Azure Pipeline that run basic continuous integration on a Terraform project

# This makes sure the pipeline is triggered every time code is pushed in the validation-testing example source, on all branches.
trigger:
- main

pool:
  vmImage: 'LinuxAgents'

steps:
- task: Bash@3
  displayName: 'Check Terraform Provider'
  inputs:
    targetType: 'inline'
    script: 'terraform init -upgrade'

#- task: Bash@3
#  displayName: 'Make Terraform Plan'
#  inputs:
#    targetType: 'inline'
#    script: 'echo Hello2'
#    script: 'terraform plan -out main.tfplan'

#- task: Bash@3
#  displayName: 'Deploy from Terraform Plan'
#  inputs:
#    targetType: 'inline'
#    script: 'echo Hello3'
#    script: 'terraform apply main.tfplan'