# Azure Pipeline that run basic continuous integration on a Terraform project

# This makes sure the pipeline is triggered every time code is pushed in the validation-testing example source, on all branches.
trigger:
- main

pool:
  vmImage: 'LinuxAgents'

stages:
- stage: Check
  displayName: 'Check Terraform Providor'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'terraform init -upgrade'

- stage: Plan
  displayName: 'Make Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'terraform plan -out main.tfplan'

- stage: Deploy
  displayName: 'Deploy from Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'terraform apply main.tfplan'