trigger:
- main

pool:
  name: 'LinuxAgents'

steps:

- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/tffile'
    backendType: 'azurerm'
    backendServiceArm: 'terraform_test'
    allowTelemetryCollection: true

#- task: TerraformCLI@2
#  displayName: terraform init
#  inputs:
#    command: 'init'
#    allowTelemetryCollection: true


- task: TerraformCLI@2
  displayName: terraform plan
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/tffile'
    environmentServiceName: 'terraform_test'
#    providerAzureRmSubscriptionId: $(SUBID)
    allowTelemetryCollection: true
    publishPlanResults: 'Main.tfplan'

- task: TerraformCLI@2
  displayName: terraform apply
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/tffile'
    environmentServiceName: 'terraform_test'
#    providerAzureRmSubscriptionId: $(SUBID)
    allowTelemetryCollection: true