trigger:
- main

pool:
  name: 'LinuxAgents'

steps:
- task: TerraformCLI@2
  inputs:
    command: 'init'
    allowTelemetryCollection: true

- task: TerraformCLI@2
  inputs:
    command: 'plan'
    allowTelemetryCollection: true
    publishPlanResults: 'Main.tfplan'

- task: TerraformCLI@2
  inputs:
    command: 'apply'
    environmentServiceName: $(SUB)
    providerAzureRmSubscriptionId: $(SUBID)
    allowTelemetryCollection: true