trigger:
- main

pool:
  name: 'LinuxAgents'

steps:
- task: TerraformCLI@2
  displayName: terraform init
  inputs:
    command: 'init'
    workingDirectory: '/tffile'
    allowTelemetryCollection: true

- task: TerraformCLI@2
  displayName: terraform plan
  inputs:
    command: 'plan'
    workingDirectory: '/tffile'
    environmentServiceName: 'terraform_test'
#    providerAzureRmSubscriptionId: $(SUBID)
    allowTelemetryCollection: true
    publishPlanResults: 'Main.tfplan'

- task: TerraformCLI@2
  displayName: terraform apply
  inputs:
    command: 'apply'
    workingDirectory: '/tffile'
    environmentServiceName: 'terraform_test'
#    providerAzureRmSubscriptionId: $(SUBID)
    allowTelemetryCollection: true