# This makes sure the pipeline is triggered every time code is pushed in the validation-testing example source, on all branches.
trigger:
- main

stages:
  - stage: TerraformContinuousIntegration
    displayName: Terraform Module - CI
    jobs:
    - job: TerraformContinuousIntegrationJob
      displayName: TerraformContinuousIntegration - CI Job
      pool:
        name: 'LinuxAgents'
      steps:
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/tffile'
          backendAzureRmUseEnvironmentVariablesForAuthentication: true
          backendAzureRmUseEntraIdForAuthentication: true
          backendServiceArm: 'azurecreate'
          backendAzureRmResourceGroupName: 'MI'
          backendAzureRmStorageAccountName: 'infradevopssa'
          backendAzureRmContainerName: 'infradevopscontainer'
          backendAzureRmKey: 'tf/terraform.tfstate'
          ARM_CLIENT_ID: $(ARM_SECRET_ID)
          ARM_CLIENT_SECRET: $(ARM_SECRET)