# This makes sure the pipeline is triggered every time code is pushed in the validation-testing example source, on all branches.
trigger:
- main

variables:
  # There must be an Azure Service Connection with that name defined in your Azure DevOps settings. See https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops
  serviceConnection: 'azurecreate'
  # Terraform settings
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/tffile'
  terraformVersion: 'latest'

stages:
  - stage: TerraformContinuousIntegration
    displayName: Terraform Module - CI
    jobs:
    - job: TerraformContinuousIntegrationJob
      displayName: TerraformContinuousIntegration - CI Job
      pool:
        name: 'LinuxAgents'
      steps:
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendAzureRmUseEnvironmentVariablesForAuthentication: true
          backendAzureRmUseEntraIdForAuthentication: true
          backendServiceArm: 'azurecreate'
          backendAzureRmResourceGroupName: 'MI'
          backendAzureRmStorageAccountName: 'infradevopssa'
          backendAzureRmContainerName: 'infradevopscontainer'
          backendAzureRmKey: 'infrastate'